name: pgmpy
on: [push]
jobs:
  build:
    name: Running tests - OS - ${{ matrix.os }}; Python - ${{ matrix.python-version}}
    runs-on: ${{ matrix.os }}
    strategy:
      max-parallel: 6
      matrix:
        python-version: [3.6, 3.7, 3.8, 3.9]
        os: [ubuntu-latest, windows-latest, macOS-latest]

    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          pip install pip -U
          pip install black -U
          black --diff .
          black --check .
          pip install -r requirements.txt -U
      - name: Print environment info
        run: | 
          which python
          pip freeze
      - name: Run tests
        run: ./run_tests.py
      - name: After success
        run: codecov
